version: "3.9"

services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quotes
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
  application:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/quotes"
    depends_on: [database]