services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=quotes
      - MYSQL_USER=root
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db-data:/var/lib/mysql/data
  gateway3:
    build: .
    environment:
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/spring_datasource_password
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
secrets:
  db_root_password:
    file: ./password.txt
  db_password:
    file: ./password.txt
  spring_datasource_password:
    file: ./password.txt
volumes:
  db-data: {}