services:
  application:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.8.2
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: { }
secrets:
  db-password:
    file: ./password.txt